### ISSUE TITLE
Write access from a non domain-joined machine

### ISSUE THREAD

**Issue by jsdhasfedssad** [NetSPI/PowerHuntShares#2]
Hi,

Thank you for this tool!

During my testing of this tool I collected the data using Runas on a non domain-joined Windows machine. According to the output there was a share named "C", not "C$", owned by "NT SERVICE\TrustedInstaller" to which "Authenticated Users" had "GenericWrite" access among other rights. I have seen your comment "Authenticated Users contains Domain Users on domain joined systems" in the Vocubulary section so I guess that is the reason for me to only get Read access. Is that correct?

Still, I attempted to get write access using Runas, PSRemoting, SMBMap, the "mount" command in Linux and PTH in Mimikatz which all can be used to impersonate/authenticate as domain accounts from non domain-joined machines, Windows and Linux. However, none of the tools got me write access... Is there any way I can get write access from a non domain-joined machine? Or is this, "odd" share, at least to me, treated in a special way?

Thanks!

**Comment by nullbind** [comment]
When accessing shares across the network two sets of permissions are evaluated.  The share permissions and the NTFS permissions, and the most restrictive wins. Right now the PowerHuntShares script only displays the enumerated ntfs permissions. So my guess is that there is a more restrictive share permission.

I'll add showing share and resultant access to my list of features to add though.  Thanks for the question!
