### ISSUE TITLE
hard coded netspi.local

### ISSUE THREAD

**Issue by techspence** [NetSPI/PowerHuntShares#4]
`netspi.local` is hard coded in two locations:

https://github.com/NetSPI/PowerHuntShares/blob/9c944c659dc2e9595d6840b2556e16c943b622df/PowerHuntShares.psm1#L2692

and

https://github.com/NetSPI/PowerHuntShares/blob/9c944c659dc2e9595d6840b2556e16c943b622df/PowerHuntShares.psm1#L3929

The result of the first hard coded value is a dead link when attempting to `Download Details` from the Dashboard.

The result of the second is not showing the actual domain scanned in the `Collection Approach` description.

**Comment by nullbind** [comment]
Thanks for the heads up! I'll get that cleaned up.

**Comment by nullbind** [comment]
ok, that one should be cleaned up.  Let me know if you run into any issues though.
